### ISSUE TITLE
No results when using wildcards with JSON 

### ISSUE THREAD

**Issue by Obsecurus** [GreyNoise-Intelligence/pygreynoise#166]
`greynoise -o json "raw_data.web.paths:*phpunit*"` produces no results
`greynoise "raw_data.web.paths:*phpunit*"` produces results

**Comment by andrew-morris** [comment]
turns out this was actually a usage issue. here's the proper syntax, which yields no error:

`$ greynoise query -f json "raw_data.web.paths:*phpunit*"`
