### ISSUE TITLE
JSON format from raw to newline delimited JSON for easy parsing

### ISSUE THREAD

**Issue by andrew-morris** [GreyNoise-Intelligence/pygreynoise#180]

**Comment by andrew-morris** [comment]
I took a quick pass at this, but my Python is pretty rusty. Opening a PR.

**Comment by bradchiappetta** [comment]
@andrew-morris : Can you elaborate on what you want to solve with this?  I'm not following the request.

**Comment by andrew-morris** [comment]
ah, yes.

so the JSON format we output with `-f json` into stdout is currently:

```
[
  {
    "complete": false,
    "count": 388050,
    "data": [
      {
        "actor": "unknown",
        "classification": "malicious",
        "cve": [],
        "first_seen": "2020-11-21",
...
```

It's a list, then a dict key (`data`) then a list of records. This is funky to parse with jq, so I think we should change the JSON format in the CLI to be newline delimited JSON. So instead it would just be:

```
{"ip": "1.1.1.1", "blah": "blah"}
{"ip": "1.1.1.1", "blah": "blah"}
{"ip": "1.1.1.1", "blah": "blah"}
```

which allows me to easily pass to jq as a CLI user
