### ISSUE TITLE
[Feature Request] Support for http proxy

### ISSUE THREAD

**Issue by shivang-crest** [GreyNoise-Intelligence/pygreynoise#358]
It seems the SDK currently doesn't support http proxy. 
This feature is crucial as most on-prem deployments would need proxy support.

**Comment by bradchiappetta** [comment]
@guillermo-menjivar : Here is an open-source example of a python package for Virustotal that includes Proxy Support:

https://github.com/dbrennand/virustotal-python/blob/master/virustotal_python/virustotal.py

**Comment by guillermo-menjivar** [comment]
Thanks @bradchiappetta, I will be working on this over the weekend
